# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 791, 531))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setGeometry(QtCore.QRect(0, 450, 631, 41))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(640, 450, 141, 41))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(400, 10, 381, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setGeometry(QtCore.QRect(10, 30, 271, 34))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 60, 271, 34))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 90, 271, 34))
        self.checkBox_3.setObjectName("checkBox_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(400, 230, 381, 211))
        self.groupBox_3.setObjectName("groupBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_4.setGeometry(QtCore.QRect(10, 30, 271, 34))
        self.checkBox_4.setObjectName("checkBox_4")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 381, 431))
        self.groupBox.setObjectName("groupBox")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 201, 41))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 201, 41))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 201, 41))
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setGeometry(QtCore.QRect(240, 30, 101, 41))
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_2.setGeometry(QtCore.QRect(240, 80, 101, 41))
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_3.setGeometry(QtCore.QRect(240, 130, 101, 41))
        self.spinBox_3.setObjectName("spinBox_3")
        self.groupBox.raise_()
        self.progressBar.raise_()
        self.pushButton.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 771, 71))
        self.groupBox_4.setObjectName("groupBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_5.setGeometry(QtCore.QRect(10, 30, 99, 34))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_6.setGeometry(QtCore.QRect(220, 30, 99, 34))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_7.setGeometry(QtCore.QRect(440, 30, 99, 34))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_8.setGeometry(QtCore.QRect(650, 30, 99, 34))
        self.checkBox_8.setObjectName("checkBox_8")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 90, 381, 191))
        self.groupBox_5.setObjectName("groupBox_5")
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_9.setGeometry(QtCore.QRect(10, 30, 121, 34))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_10.setGeometry(QtCore.QRect(10, 60, 131, 34))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_11.setGeometry(QtCore.QRect(10, 90, 141, 34))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_12.setGeometry(QtCore.QRect(10, 120, 191, 34))
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_13.setGeometry(QtCore.QRect(10, 150, 141, 34))
        self.checkBox_13.setObjectName("checkBox_13")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 290, 381, 191))
        self.groupBox_6.setObjectName("groupBox_6")
        self.checkBox_16 = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_16.setGeometry(QtCore.QRect(10, 30, 121, 34))
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_17.setGeometry(QtCore.QRect(10, 60, 131, 34))
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_18.setGeometry(QtCore.QRect(10, 90, 141, 34))
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_19 = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_19.setGeometry(QtCore.QRect(10, 120, 191, 34))
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_20 = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_20.setGeometry(QtCore.QRect(10, 150, 141, 34))
        self.checkBox_20.setObjectName("checkBox_20")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(400, 90, 381, 191))
        self.groupBox_7.setObjectName("groupBox_7")
        self.checkBox_14 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_14.setGeometry(QtCore.QRect(10, 30, 131, 34))
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_23 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_23.setGeometry(QtCore.QRect(10, 60, 141, 34))
        self.checkBox_23.setObjectName("checkBox_23")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_8.setGeometry(QtCore.QRect(400, 290, 381, 191))
        self.groupBox_8.setObjectName("groupBox_8")
        self.checkBox_21 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_21.setGeometry(QtCore.QRect(10, 30, 131, 34))
        self.checkBox_21.setObjectName("checkBox_21")
        self.checkBox_24 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_24.setGeometry(QtCore.QRect(10, 60, 141, 34))
        self.checkBox_24.setObjectName("checkBox_24")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_17.setGeometry(QtCore.QRect(10, 10, 381, 471))
        self.groupBox_17.setObjectName("groupBox_17")
        self.label_7 = QtWidgets.QLabel(self.groupBox_17)
        self.label_7.setGeometry(QtCore.QRect(10, 30, 211, 41))
        self.label_7.setObjectName("label_7")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_17)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 30, 115, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox_17)
        self.label_8.setGeometry(QtCore.QRect(10, 80, 211, 41))
        self.label_8.setObjectName("label_8")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_17)
        self.pushButton_4.setGeometry(QtCore.QRect(250, 80, 115, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_9 = QtWidgets.QLabel(self.groupBox_17)
        self.label_9.setGeometry(QtCore.QRect(10, 130, 211, 41))
        self.label_9.setObjectName("label_9")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_17)
        self.pushButton_5.setGeometry(QtCore.QRect(250, 130, 115, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.groupBox_18 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_18.setGeometry(QtCore.QRect(400, 10, 381, 471))
        self.groupBox_18.setObjectName("groupBox_18")
        self.checkBox_45 = QtWidgets.QCheckBox(self.groupBox_18)
        self.checkBox_45.setGeometry(QtCore.QRect(10, 30, 211, 41))
        self.checkBox_45.setObjectName("checkBox_45")
        self.tabWidget.addTab(self.tab_5, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 36))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.menu.addAction(self.action)
        self.menu.addSeparator()
        self.menu.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fraction-Calc"))
        self.pushButton.setText(_translate("MainWindow", "生成"))
        self.groupBox_2.setTitle(_translate("MainWindow", "题目输出格式"))
        self.checkBox.setText(_translate("MainWindow", "tex"))
        self.checkBox_2.setText(_translate("MainWindow", "pdf"))
        self.checkBox_3.setText(_translate("MainWindow", "txt"))
        self.groupBox_3.setTitle(_translate("MainWindow", "答案输出格式"))
        self.checkBox_4.setText(_translate("MainWindow", "txt"))
        self.groupBox.setTitle(_translate("MainWindow", "基础设置"))
        self.label_4.setText(_translate("MainWindow", "题目数量（1-100）"))
        self.label_3.setText(_translate("MainWindow", "最大数值范围（1-1000）"))
        self.label.setText(_translate("MainWindow", "最小数值范围（1-1000）"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "生成器"))
        self.groupBox_4.setTitle(_translate("MainWindow", "运算符号"))
        self.checkBox_5.setText(_translate("MainWindow", "加法（+）"))
        self.checkBox_6.setText(_translate("MainWindow", "减法（-）"))
        self.checkBox_7.setText(_translate("MainWindow", "乘法（*）"))
        self.checkBox_8.setText(_translate("MainWindow", "除法（/）"))
        self.groupBox_5.setTitle(_translate("MainWindow", "加法设置"))
        self.checkBox_9.setText(_translate("MainWindow", "同分母运算"))
        self.checkBox_10.setText(_translate("MainWindow", "分母有公因数"))
        self.checkBox_11.setText(_translate("MainWindow", "答案不大于1"))
        self.checkBox_12.setText(_translate("MainWindow", "运算项均为真分数或1"))
        self.checkBox_13.setText(_translate("MainWindow", "1可以作为分母"))
        self.groupBox_6.setTitle(_translate("MainWindow", "减法设置"))
        self.checkBox_16.setText(_translate("MainWindow", "同分母运算"))
        self.checkBox_17.setText(_translate("MainWindow", "分母有公因数"))
        self.checkBox_18.setText(_translate("MainWindow", "答案不为负数"))
        self.checkBox_19.setText(_translate("MainWindow", "运算项均为真分数或1"))
        self.checkBox_20.setText(_translate("MainWindow", "1可以作为分母"))
        self.groupBox_7.setTitle(_translate("MainWindow", "乘法设置"))
        self.checkBox_14.setText(_translate("MainWindow", "结果可以约分"))
        self.checkBox_23.setText(_translate("MainWindow", "1可以作为分母"))
        self.groupBox_8.setTitle(_translate("MainWindow", "除法设置"))
        self.checkBox_21.setText(_translate("MainWindow", "结果可以约分"))
        self.checkBox_24.setText(_translate("MainWindow", "1可以作为分母"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "基础题型设置"))
        self.groupBox_17.setTitle(_translate("MainWindow", "清理文件"))
        self.label_7.setText(_translate("MainWindow", "清理latexmk中间文件"))
        self.pushButton_3.setText(_translate("MainWindow", "点我！"))
        self.label_8.setText(_translate("MainWindow", "清理配置文件（conf.json）"))
        self.pushButton_4.setText(_translate("MainWindow", "点我！"))
        self.label_9.setText(_translate("MainWindow", "清理文件夹下的题目和答案"))
        self.pushButton_5.setText(_translate("MainWindow", "点我！"))
        self.groupBox_18.setTitle(_translate("MainWindow", "其它选项"))
        self.checkBox_45.setText(_translate("MainWindow", "保留latexmk中间文件"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "高级设置"))
        self.menu.setTitle(_translate("MainWindow", "帮助"))
        self.action.setText(_translate("MainWindow", "使用帮助"))
        self.action_2.setText(_translate("MainWindow", "关于"))
        self.action_4.setText(_translate("MainWindow", "高级设置"))
